version: '2.2'
services:
  web:
    image: phundament/nginx-one:1.9-5.1.1
    environment:
      - FASTCGI_PASS_HOST=php
    ports:
      - '8200:80'
    container_name: site_nginx
    volumes:
      # Application testing
      - ../src/app/web:/app/web:delegated
